version: '3'

services:
  api:
    container_name: api-container
    image: aesedeu/api_open_innovation:1.0
    build:
      context: build/api_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres-container
    image: postgres:16.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iloveai
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"